SET NAMES 'utf8';

#####	areatrigger_tavern	#####

UPDATE `areatrigger_tavern` SET `name`='Westfall - Späherkuppe Gasthaus' WHERE (`id`='71');
UPDATE `areatrigger_tavern` SET `name`='Strahnbrad' WHERE (`id`='178');
UPDATE `areatrigger_tavern` SET `name`='Der Wald von Elwynn - Goldhain - Gasthaus zur Höhle des Löwen' WHERE (`id`='562');
UPDATE `areatrigger_tavern` SET `name`='Das Rotkammgebirge - Rathaus von Seenhain' WHERE (`id`='682');
UPDATE `areatrigger_tavern` SET `name`='Dämmerwald - Dunkelhain - Taverne Zum roten Raben' WHERE (`id`='707');
UPDATE `areatrigger_tavern` SET `name`='Vorgebirge des Hügellands - Rathaus von Süderstade' WHERE (`id`='708');
UPDATE `areatrigger_tavern` SET `name`='Die Düstermarschen - Die Insel Theramore' WHERE (`id`='709');
UPDATE `areatrigger_tavern` SET `name`='Dun Morogh - Kharanos - Brauerei Donnerbräu' WHERE (`id`='710');
UPDATE `areatrigger_tavern` SET `name`='Loch Modan - Thelsamar - Gasthof zum Starkbierlager' WHERE (`id`='712');
UPDATE `areatrigger_tavern` SET `name`='Das Sumpfland - Hafen von Menethil - Tiefenwassertaverne' WHERE (`id`='713');
UPDATE `areatrigger_tavern` SET `name`='Teldrassil - Dolanaar' WHERE (`id`='715');
UPDATE `areatrigger_tavern` SET `name`='Dunkelküste - Auberdine' WHERE (`id`='716');
UPDATE `areatrigger_tavern` SET `name`='Eschental - Astranaar' WHERE (`id`='717');
UPDATE `areatrigger_tavern` SET `name`='Tirisfal - Brill - Taverne Zur Galgenschlinge' WHERE (`id`='719');
UPDATE `areatrigger_tavern` SET `name`='Silberwald ' WHERE (`id`='720');
UPDATE `areatrigger_tavern` SET `name`='Vorgebirge des Hügellands ' WHERE (`id`='721');
UPDATE `areatrigger_tavern` SET `name`='Mulgore ' WHERE (`id`='722');
UPDATE `areatrigger_tavern` SET `name`='Das Brachland ' WHERE (`id`='742');
UPDATE `areatrigger_tavern` SET `name`='Das Brachland ' WHERE (`id`='743');
UPDATE `areatrigger_tavern` SET `name`='Durotar ' WHERE (`id`='843');
UPDATE `areatrigger_tavern` SET `name`='Die Sümpfe des Elends ' WHERE (`id`='844');
UPDATE `areatrigger_tavern` SET `name`='Schlingendorntal ' WHERE (`id`='862');
UPDATE `areatrigger_tavern` SET `name`='Das Brachland ' WHERE (`id`='982');
UPDATE `areatrigger_tavern` SET `name`='Das Steinkrallengebirge ' WHERE (`id`='1022');
UPDATE `areatrigger_tavern` SET `name`='Tanaris ' WHERE (`id`='1023');
UPDATE `areatrigger_tavern` SET `name`='Feralas ' WHERE (`id`='1024');
UPDATE `areatrigger_tavern` SET `name`='Feralas ' WHERE (`id`='1025');
UPDATE `areatrigger_tavern` SET `name`='Burg Wildhammer' WHERE (`id`='1042');
UPDATE `areatrigger_tavern` SET `name`='Das Ödland ' WHERE (`id`='1606');
UPDATE `areatrigger_tavern` SET `name`='Das Arathi Hochland ' WHERE (`id`='1646');
UPDATE `areatrigger_tavern` SET `name`='Desolace ' WHERE (`id`='2266');
UPDATE `areatrigger_tavern` SET `name`='Desolace ' WHERE (`id`='2267');
UPDATE `areatrigger_tavern` SET `name`='Tausend Nadeln ' WHERE (`id`='2286');
UPDATE `areatrigger_tavern` SET `name`='Winterquell ' WHERE (`id`='2287');
UPDATE `areatrigger_tavern` SET `name`='Eschental ' WHERE (`id`='2610');
UPDATE `areatrigger_tavern` SET `name`='Sturmwind backup rest' WHERE (`id`='2786');
UPDATE `areatrigger_tavern` SET `name`='Unterstadt' WHERE (`id`='3547');
UPDATE `areatrigger_tavern` SET `name`='Dorf der Bruchhauer' WHERE (`id`='3690');
UPDATE `areatrigger_tavern` SET `name`='Basislager von Grom''gol' WHERE (`id`='3886');
UPDATE `areatrigger_tavern` SET `name`='Burg Cenarius' WHERE (`id`='3985');
UPDATE `areatrigger_tavern` SET `name`='Kapelle des hoffnungsvollen Lichts' WHERE (`id`='4058');
UPDATE `areatrigger_tavern` SET `name`='Der Steinkrallengipfel' WHERE (`id`='4090');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Tranquillien' WHERE (`id`='4108');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Azurwacht' WHERE (`id`='4240');
UPDATE `areatrigger_tavern` SET `name`='Blutmythosinsel - Gasthaus der Blutwacht' WHERE (`id`='4241');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Thrallmar' WHERE (`id`='4336');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Ehrenfeste' WHERE (`id`='4337');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Zabra''Jin' WHERE (`id`='4373');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Telredor' WHERE (`id`='4374');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Garadar' WHERE (`id`='4375');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Telaar' WHERE (`id`='4376');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Allerias Feste' WHERE (`id`='4377');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Temples von Thelamat' WHERE (`id`='4381');
UPDATE `areatrigger_tavern` SET `name`='Zuflucht des Cenarius' WHERE (`id`='4382');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Oreborzuflucht' WHERE (`id`='4383');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Falkenplatzes' WHERE (`id`='4486');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Donnerfeste' WHERE (`id`='4494');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Sylvanaar' WHERE (`id`='4499');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Area 52' WHERE (`id`='4521');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Schattenmond' WHERE (`id`='4526');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Wildhammerfeste' WHERE (`id`='4528');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus der Sturmsäule' WHERE (`id`='4555');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Toshleys Station' WHERE (`id`='4558');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Altars der Sha''tar' WHERE (`id`='4577');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Mok''Nathal' WHERE (`id`='4595');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Sanktums der Sterne' WHERE (`id`='4607');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Ewigen Hains' WHERE (`id`='4640');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus des Morastwinkels' WHERE (`id`='4714');
UPDATE `areatrigger_tavern` SET `name`='Eisenschmiede' WHERE (`id`='4769');
UPDATE `areatrigger_tavern` SET `name`='Gasthaus von Brackenwall' WHERE (`id`='4775');
UPDATE `areatrigger_tavern` SET `name`='Insel von Quel''Danas, Gasthof beim Hafen der Sonnenweiten' WHERE (`id`='4847');




#####	areatrigger_teleport	#####

UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Friedhof (Eingang)' WHERE (`id`='45');
UPDATE `areatrigger_teleport` SET `name`='Todesminen Eingang' WHERE (`id`='78');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind Verlies Eingang' WHERE (`id`='101');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind Gruft Eingang' WHERE (`id`='107');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind Gruft Instanz' WHERE (`id`='109');
UPDATE `areatrigger_teleport` SET `name`='Todesminen Instanz Start' WHERE (`id`='119');
UPDATE `areatrigger_teleport` SET `name`='Todesminen Instanz Ende' WHERE (`id`='121');
UPDATE `areatrigger_teleport` SET `name`='Burg Schattenfang Eingang' WHERE (`id`='145');
UPDATE `areatrigger_teleport` SET `name`='Burg Schattenfang - Eingang' WHERE (`id`='194');
UPDATE `areatrigger_teleport` SET `name`='Das Brachland - Die Höhlen des Wehklagens' WHERE (`id`='226');
UPDATE `areatrigger_teleport` SET `name`='Das Brachland - Die Höhlen des Wehklagens' WHERE (`id`='228');
UPDATE `areatrigger_teleport` SET `name`='Kral der Klingenhauer Instanz Start' WHERE (`id`='242');
UPDATE `areatrigger_teleport` SET `name`='Kral der Klingenhauer Eingang' WHERE (`id`='244');
UPDATE `areatrigger_teleport` SET `name`='Tiefschwarze Grotte Eingang' WHERE (`id`='257');
UPDATE `areatrigger_teleport` SET `name`='Tiefschwarze Grotte Instanz Start' WHERE (`id`='259');
UPDATE `areatrigger_teleport` SET `name`='Uldaman Eingang' WHERE (`id`='286');
UPDATE `areatrigger_teleport` SET `name`='Uldaman Instanz Start' WHERE (`id`='288');
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Instanz Start' WHERE (`id`='322');
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Eingang' WHERE (`id`='324');
UPDATE `areatrigger_teleport` SET `name`='Hügel der Klingenhauer Eingang' WHERE (`id`='442');
UPDATE `areatrigger_teleport` SET `name`='Hügel der Klingenhauer Instanz Start' WHERE (`id`='444');
UPDATE `areatrigger_teleport` SET `name`='Altar von Atal''Hakkar Eingang' WHERE (`id`='446');
UPDATE `areatrigger_teleport` SET `name`='Altar von Atal''Hakkar Instanz Start' WHERE (`id`='448');
UPDATE `areatrigger_teleport` SET `name`='Das Verlies - Instanz' WHERE (`id`='503');
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Eisenbahn Depot Eingang' WHERE (`id`='523');
UPDATE `areatrigger_teleport` SET `name`='Gnomeregan Eisenbahn Depot Instanz' WHERE (`id`='525');
UPDATE `areatrigger_teleport` SET `name`='Teldrassil - Ruth Theran' WHERE (`id`='527');
UPDATE `areatrigger_teleport` SET `name`='Teldrassil - Darnassus' WHERE (`id`='542');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Friedhof (Ausgang)' WHERE (`id`='602');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Kathedrale (Ausgang)' WHERE (`id`='604');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Waffenkammer (Ausgang)' WHERE (`id`='606');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Bibliothek (Ausgang)' WHERE (`id`='608');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Kathedrale (Eingang)' WHERE (`id`='610');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Waffenkammer (Eingang)' WHERE (`id`='612');
UPDATE `areatrigger_teleport` SET `name`='Das Scharlachrote Kloster - Bibliothek (Eingang)' WHERE (`id`='614');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind - Heiliger Raum der Hexenmeister' WHERE (`id`='702');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind - Heiliges Turmportal der Hexenmeister' WHERE (`id`='704');
UPDATE `areatrigger_teleport` SET `name`='Uldaman Instanz Ende' WHERE (`id`='882');
UPDATE `areatrigger_teleport` SET `name`='Uldaman Ausgang' WHERE (`id`='902');
UPDATE `areatrigger_teleport` SET `name`='Zul''Farrak Instanz Start' WHERE (`id`='922');
UPDATE `areatrigger_teleport` SET `name`='Zul''Farrak Eingang' WHERE (`id`='924');
UPDATE `areatrigger_teleport` SET `name`='Sprung des Glaubens - Ende der Steigung' WHERE (`id`='943');
UPDATE `areatrigger_teleport` SET `name`='Onyxias Unterschlupf - Düstermarschen Instanz' WHERE (`id`='1064');
UPDATE `areatrigger_teleport` SET `name`='Der Schwarzfels - Die sengende Schlucht Instanz?' WHERE (`id`='1466');
UPDATE `areatrigger_teleport` SET `name`='Schwarzfelsspitze - Die sengende Schlucht Instanz (Innen)' WHERE (`id`='1468');
UPDATE `areatrigger_teleport` SET `name`='Schwarzfelsspitze - Die sengende Schlucht Instanz' WHERE (`id`='1470');
UPDATE `areatrigger_teleport` SET `name`='Schwarzfelstiefen - Die sengende Schlucht Instanz' WHERE (`id`='1472');
UPDATE `areatrigger_teleport` SET `name`='Tiefenbahn - Eisenschmiede Instanz (Innen)' WHERE (`id`='2166');
UPDATE `areatrigger_teleport` SET `name`='Tiefenbahn - Sturmwind Instanz (Innen)' WHERE (`id`='2171');
UPDATE `areatrigger_teleport` SET `name`='Tiefenbahn - Sturmwind Instanz' WHERE (`id`='2173');
UPDATE `areatrigger_teleport` SET `name`='Tiefenbahn - Eisenschmiede Instanz' WHERE (`id`='2175');
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Die östlichen Pestländer Instanz' WHERE (`id`='2214');
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Die östlichen Pestländer Instanz' WHERE (`id`='2216');
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Die östlichen Pestländer Instanz' WHERE (`id`='2217');
UPDATE `areatrigger_teleport` SET `name`='Stratholme - Die östlichen Pestländer Instanz (Innen)' WHERE (`id`='2221');
UPDATE `areatrigger_teleport` SET `name`='Der Flammenschlund - Ogrimmar Instanz (Innen)' WHERE (`id`='2226');
UPDATE `areatrigger_teleport` SET `name`='Der Flammenschlund - Ogrimmar Instanz' WHERE (`id`='2230');
UPDATE `areatrigger_teleport` SET `name`='Alteractal - Allianz Eingang' WHERE (`id`='2412');
UPDATE `areatrigger_teleport` SET `name`='Alteractal - Horde Eingang' WHERE (`id`='2413');
UPDATE `areatrigger_teleport` SET `name`='Halle der Legenden - Ogrimmar' WHERE (`id`='2527');
UPDATE `areatrigger_teleport` SET `name`='Halle der Legenden - Ogrimmar (Innen)' WHERE (`id`='2530');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind - Halle der Champions' WHERE (`id`='2532');
UPDATE `areatrigger_teleport` SET `name`='Sturmwind (Innen) - Halle der Champions' WHERE (`id`='2534');
UPDATE `areatrigger_teleport` SET `name`='Scholomance Eingang' WHERE (`id`='2567');
UPDATE `areatrigger_teleport` SET `name`='Scholomance Instanz' WHERE (`id`='2568');
UPDATE `areatrigger_teleport` SET `name`='Alteractal - Horde Ausgang' WHERE (`id`='2606');
UPDATE `areatrigger_teleport` SET `name`='Alteractal - Allianz Ausgang' WHERE (`id`='2608');
UPDATE `areatrigger_teleport` SET `name`='Onyxias Unterschlupf Eingang' WHERE (`id`='2848');
UPDATE `areatrigger_teleport` SET `name`='Die geschmolzene Brücke' WHERE (`id`='2886');
UPDATE `areatrigger_teleport` SET `name`='Der geschmolzene Kern (Eingang)' WHERE (`id`='2890');
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE (`id`='3126');
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE (`id`='3131');
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE (`id`='3133');
UPDATE `areatrigger_teleport` SET `name`='Maraudon' WHERE (`id`='3134');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3183');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3184');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3185');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3186');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3187');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3189');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3190');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3191');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3193');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3194');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3195');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3196');
UPDATE `areatrigger_teleport` SET `name`='Düsterbruch' WHERE (`id`='3197');
UPDATE `areatrigger_teleport` SET `name`='Der geschmolzene Kern Fenster Eingang' WHERE (`id`='3528');
UPDATE `areatrigger_teleport` SET `name`='Der geschmolzene Kern Fenster(Lava) Eingang' WHERE (`id`='3529');
UPDATE `areatrigger_teleport` SET `name`='Eschental - Hain von Silberwingen (Kriegshymnenschlucht - Allianz Eingang)' WHERE (`id`='3650');
UPDATE `areatrigger_teleport` SET `name`='Das Brachland - Mor''shan Stützpunkt (Kriegshymnenschlucht - Horde Eingang)' WHERE (`id`='3654');
UPDATE `areatrigger_teleport` SET `name`='Pechschwingenhort - Schwarzfels - Die östlichen Königreiche' WHERE (`id`='3726');
UPDATE `areatrigger_teleport` SET `name`='Der Schwarzfels - Unbekannt' WHERE (`id`='3728');
UPDATE `areatrigger_teleport` SET `name`='Zul''Gurub Eingang ' WHERE (`id`='3928');
UPDATE `areatrigger_teleport` SET `name`='Zul''Gurub Ausgang ' WHERE (`id`='3930');
UPDATE `areatrigger_teleport` SET `name`='Arathibecken Allianz Ausgang' WHERE (`id`='3948');
UPDATE `areatrigger_teleport` SET `name`='Arathibecken Horde Ausgang' WHERE (`id`='3949');
UPDATE `areatrigger_teleport` SET `name`='Arathibecken Allianz Eingang' WHERE (`id`='3953');
UPDATE `areatrigger_teleport` SET `name`='Arathibecken Horde Eingang' WHERE (`id`='3954');
UPDATE `areatrigger_teleport` SET `name`='Ruinen Von Ahn''Qiraj (Innen)' WHERE (`id`='4006');
UPDATE `areatrigger_teleport` SET `name`='Ruinen Von Ahn''Qiraj (Außen)' WHERE (`id`='4008');
UPDATE `areatrigger_teleport` SET `name`='Tempel von Ahn''Qiraj (Außen)' WHERE (`id`='4010');
UPDATE `areatrigger_teleport` SET `name`='Tempel von Ahn''Qiraj (Innen)' WHERE (`id`='4012');
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Außen)' WHERE (`id`='4055');
UPDATE `areatrigger_teleport` SET `name`='Karazhan - Das Pförtnerhaus (Eingang)' WHERE (`id`='4131');
UPDATE `areatrigger_teleport` SET `name`='Karazhan, Hintereingang' WHERE (`id`='4135');
UPDATE `areatrigger_teleport` SET `name`='Die zerschmetterten Hallen Hauptausgang' WHERE (`id`='4145');
UPDATE `areatrigger_teleport` SET `name`='Der Blutkessel Hauptausgang' WHERE (`id`='4147');
UPDATE `areatrigger_teleport` SET `name`='Magtheridons Unterschlupf Hauptausgang' WHERE (`id`='4149');
UPDATE `areatrigger_teleport` SET `name`='Höllenfeuerbollwerk Eingang' WHERE (`id`='4150');
UPDATE `areatrigger_teleport` SET `name`='Die zerschmetterten Hallen Eingang' WHERE (`id`='4151');
UPDATE `areatrigger_teleport` SET `name`='Der Blutkessel Eingang' WHERE (`id`='4152');
UPDATE `areatrigger_teleport` SET `name`='Magtheridons Unterschlupf' WHERE (`id`='4153');
UPDATE `areatrigger_teleport` SET `name`='Naxxramas (Innen)' WHERE (`id`='4156');
UPDATE `areatrigger_teleport` SET `name`='Höllenfeuerbollwerk Hauptausgang' WHERE (`id`='4297');
UPDATE `areatrigger_teleport` SET `name`='Hyjalgipfel, Allianzstartpunkt' WHERE (`id`='4311');
UPDATE `areatrigger_teleport` SET `name`='Hyjalgipfel, Hordestartpunkt' WHERE (`id`='4312');
UPDATE `areatrigger_teleport` SET `name`='Hyjalgipfel, Nachtelfenstartpunkt' WHERE (`id`='4313');
UPDATE `areatrigger_teleport` SET `name`='Höhlen der Zeit, Kampf um den Hyjalgipfel' WHERE (`id`='4319');
UPDATE `areatrigger_teleport` SET `name`='Höhlen der Zeit, Der schwarze Morast - Eingang', `required_failed_text`='Ihr könnt den schwarzen Morast nicht betreten bis Ihr Thrall aus der Burg Durnholde gerettet habt.' WHERE (`id`='4320');
UPDATE `areatrigger_teleport` SET `name`='Höhlen der Zeit, Altes Vorgebirge des Hügellands - Eingang' WHERE (`id`='4321');
UPDATE `areatrigger_teleport` SET `name`='Höhlen der Zeit, Der schwarze Morast - Ausgang' WHERE (`id`='4322');
UPDATE `areatrigger_teleport` SET `name`='Hyjalgipfel - Ausgang' WHERE (`id`='4323');
UPDATE `areatrigger_teleport` SET `name`='Höhlen der Zeit, Altes Vorgebirge des Hügellands - Ausgang' WHERE (`id`='4324');
UPDATE `areatrigger_teleport` SET `name`='Scherbenwelt zum Dunklen Portal' WHERE (`id`='4352');
UPDATE `areatrigger_teleport` SET `name`='Dunkles Portal zur Scherbenwelt' WHERE (`id`='4354');
UPDATE `areatrigger_teleport` SET `name`='Der Tiefensumpf' WHERE (`id`='4363');
UPDATE `areatrigger_teleport` SET `name`='Die Dampfkammer' WHERE (`id`='4364');
UPDATE `areatrigger_teleport` SET `name`='Die Sklavenunterkünfte' WHERE (`id`='4365');
UPDATE `areatrigger_teleport` SET `name`='Die Dampfkammer, Haupteingang' WHERE (`id`='4366');
UPDATE `areatrigger_teleport` SET `name`='Der Tiefensumpf, Haupteingang' WHERE (`id`='4367');
UPDATE `areatrigger_teleport` SET `name`='Zangarmarschen - Schlangensee - Entdeckung? komisch' WHERE (`id`='4379');
UPDATE `areatrigger_teleport` SET `name`='Insel der Sonnenwanderer nach östliche Pestländer' WHERE (`id`='4386');
UPDATE `areatrigger_teleport` SET `name`='Schattenlabyrinth, Hauptausgang' WHERE (`id`='4397');
UPDATE `areatrigger_teleport` SET `name`='Sethekkhallen, Hauptausgang' WHERE (`id`='4399');
UPDATE `areatrigger_teleport` SET `name`='Managruft, Hauptausgang' WHERE (`id`='4401');
UPDATE `areatrigger_teleport` SET `name`='Auchenaikrypta, Hauptausgang' WHERE (`id`='4403');
UPDATE `areatrigger_teleport` SET `name`='Auchenaikrypta, Haupteingang' WHERE (`id`='4404');
UPDATE `areatrigger_teleport` SET `name`='Managruft, Haupteingang' WHERE (`id`='4405');
UPDATE `areatrigger_teleport` SET `name`='Sethekkhallen, Haupteingang' WHERE (`id`='4406');
UPDATE `areatrigger_teleport` SET `name`='Schattenlabyrinth, Haupteingang' WHERE (`id`='4407');
UPDATE `areatrigger_teleport` SET `name`='Östliche Pestländer nach Insel der Sonnenwanderer' WHERE (`id`='4409');
UPDATE `areatrigger_teleport` SET `name`='Schlangenschrein Innen' WHERE (`id`='4416');
UPDATE `areatrigger_teleport` SET `name`='Echsenkessel Außen' WHERE (`id`='4418');
UPDATE `areatrigger_teleport` SET `name`='Karazhan, Hauptausgang' WHERE (`id`='4436');
UPDATE `areatrigger_teleport` SET `name`='Arkatraz, Hauptausgang' WHERE (`id`='4455');
UPDATE `areatrigger_teleport` SET `name`='Phoenixhalle, Hauptausgang' WHERE (`id`='4457');
UPDATE `areatrigger_teleport` SET `name`='Botanikum, Hauptausgang' WHERE (`id`='4459');
UPDATE `areatrigger_teleport` SET `name`='Mechanar, Hauptausgang' WHERE (`id`='4461');
UPDATE `areatrigger_teleport` SET `name`='Botanikum, Haupteingang' WHERE (`id`='4467');
UPDATE `areatrigger_teleport` SET `name`='Arkatraz, Haupteingang' WHERE (`id`='4468');
UPDATE `areatrigger_teleport` SET `name`='Mechanar, Haupteingang' WHERE (`id`='4469');
UPDATE `areatrigger_teleport` SET `name`='Phoenixhalle, Haupteingang' WHERE (`id`='4470');
UPDATE `areatrigger_teleport` SET `name`='Hyjalgipfel, Ausgang' WHERE (`id`='4487');
UPDATE `areatrigger_teleport` SET `name`='Socrethar''s Sitz zum Kontinent' WHERE (`id`='4523');
UPDATE `areatrigger_teleport` SET `name`='Gruuls Unterschlupf, Hauptausgang' WHERE (`id`='4534');
UPDATE `areatrigger_teleport` SET `name`='Gruuls Unterschlupf, Haupteingang' WHERE (`id`='4535');
UPDATE `areatrigger_teleport` SET `name`='Invasionpunkt, Katastrophe (Rückkehr)' WHERE (`id`='4561');
UPDATE `areatrigger_teleport` SET `name`='Invasionpunkt, Katastrophe (Rückkehr)' WHERE (`id`='4562');
UPDATE `areatrigger_teleport` SET `name`='Schattenmondtal - Schwarzer Tempel' WHERE (`id`='4598');
UPDATE `areatrigger_teleport` SET `name`='Schwarzer Tempel - Schattenmondtal' WHERE (`id`='4619');
UPDATE `areatrigger_teleport` SET `name`='Zul''Aman, Haupteingang' WHERE (`id`='4738');
UPDATE `areatrigger_teleport` SET `name`='Zul''Aman, Hauptausgang' WHERE (`id`='4739');
UPDATE `areatrigger_teleport` SET `name`='Terrasse der Magister, Ausgang' WHERE (`id`='4885');
UPDATE `areatrigger_teleport` SET `name`='Terrasse der Magister, Eingang' WHERE (`id`='4887');
UPDATE `areatrigger_teleport` SET `name`='Sonnenbrunnenplateau, Eingang' WHERE (`id`='4889');
UPDATE `areatrigger_teleport` SET `name`='Sonnenbrunnenplateau, Ausgang' WHERE (`id`='4891');

#####	transports	#####

UPDATE `transports` SET `name`='Ratschet und Beutebucht' WHERE (`entry`='20808');
UPDATE `transports` SET `name`='Orgrimmar und Unterstadt' WHERE (`entry`='164871');
UPDATE `transports` SET `name`='Basislager von Grom''gol und Orgrimmar' WHERE (`entry`='175080');
UPDATE `transports` SET `name`='Hafen von Menethil und Insel Theramore' WHERE (`entry`='176231');
UPDATE `transports` SET `name`='Teldrassil und Auberdine' WHERE (`entry`='176244');
UPDATE `transports` SET `name`='Hafen von Menethil und Auberdine' WHERE (`entry`='176310');
UPDATE `transports` SET `name`='Basislager von Grom''gol und Unterstadt' WHERE (`entry`='176495');
UPDATE `transports` SET `name`='Vergessene Küste und Mondfederfeste' WHERE (`entry`='177233');
UPDATE `transports` SET `name`='Azurmythosinsel und Auberdine' WHERE (`entry`='181646');

SET NAMES 'latin1';
